### ISSUE TITLE
inconsistent API for __getitem__ and __setitem__

### ISSUE THREAD

**Issue by hainm** [pytraj/pytraj#319]
traj['@CA'] return a new (copied)`Trajectory` with stripped atoms.

traj['@CA'] = xyz # assign coords for `CA` atoms

**Comment by hainm** [comment]
may be we need to make a method

traj.update_coords(mask. xyz)
```python
traj[0:3].update_coords(mask, xyz)
```

**Comment by swails** [comment]
This isn't inconsistent IMO.  numpy behaves similarly (although it is a view rather than a copy).  But the Python `list` behaves *just* like this:

```Python
x = [0, 1, 2, 3, 4, 5]
x[1:3] # Returns a copy of just [1, 2]
x[1:3] = [2, 2] # Sets x to [0, 2, 2, 3, 4, 5]
```

What you have now is intuitive to me.

**Comment by hainm** [comment]
@swails: great. I will keep them. thanks.

**Comment by hainm** [comment]
closed since problem solved.
