### ISSUE TITLE
inconsistent result pytraj vs cpptraj

### ISSUE THREAD

**Issue by hainm** [pytraj/pytraj#485]
this happen when combining `autoimage` and `rmsfit` at the same time. 

use only `autoimage`: match (rmsd<1E-10)
use only `rmsfit`: match

but if combining them, rmsd=0.6 to saved cpptraj traj. ack.

```python
In [8]: import pytraj as pt

In [9]: traj = pt.iterload(['./data/tz2.ortho.nc', ], './data/tz2.ortho.parm7')

In [10]: xyz = pt.get_coordinates(traj(autoimage=True, rmsfit=(0, '@CA,C,N'))
)

In [11]: saved_traj = pt.iterload('./data/tz2.autoimage_with_rmsfit.nc', traj.top)

In [12]: rmsd(saved_traj.xyz, xyz)
Out[12]: 0.6349591011653271
```

all frames were shifted (vs saved traj from cpptraj)
rmsd
```
0.6349589654298733
0.6349591258302947
0.6349591168337528
0.6349591280414643
0.6349591161553934
0.634959115164595
0.6349591093341331
0.6349591142336568
0.6349591255565542
0.6349591065071268
```

**Comment by hainm** [comment]
this does not happen with `Trajectory` (mutable) class.

```python
In [13]: traj_mut = traj[:]
In [15]: traj_mut.autoimage()
In [16]: traj_mut.rmsfit(mask='@CA,N,C')
In [17]: rmsd(saved_traj.xyz, traj_mut.xyz)
Out[17]: 5.75140630497023e-07
```

**Comment by swails** [comment]
Order matters here.  Once you RMS-fit, imaging doesn't work.  Maybe your first example is RMS-fitting, then autoimaging?

**Comment by hainm** [comment]
@swails 
 It seems that when iterating frame for TrajectoryIterator, I did the imaging first.
https://github.com/pytraj/pytraj/blob/master/pytraj/core/frameiter.py#L58

 I always have trouble debugging things related to `rms or rmsd` because it changes coordinates of frame and reference frame. I need to double-check above code, must be mistaken somewhere.

**Comment by hainm** [comment]
oops, I just updated above link.

**Comment by hainm** [comment]
@swails 
now I know why, I did not do `autoimage` for the reference structure before do fitting. :D
